actions test 30

diff --git a/.github/workflows/Vendor.yml b/.github/workflows/Vendor.yml
--- a/.github/workflows/Vendor.yml
+++ b/.github/workflows/Vendor.yml
@@ -17,6 +17,7 @@ on:
 
 jobs:
   vendor:
+    if: ${{ github.repository == 'staticlibs/duckdb-odbc' }}
     runs-on: ubuntu-latest
     outputs:
       sha: ${{ steps.commit.outputs.sha }}
@@ -25,76 +26,124 @@ jobs:
     name: "Update Vendored Sources"
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        id: setup_python
+        with:
+          python-version: '3.12'
+
+      - name: Set up GitHub CLI
+        uses: cli/gh-action@v2
+
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
-      - uses: actions/checkout@v4
+      - name: Checkout engine
+        uses: actions/checkout@v4
+        id: checkout_engine
         with:
           repository: duckdb/duckdb
           path: .git/duckdb
           fetch-depth: 0
 
-      - name: Get commit SHA
+      - name: Checkout engine rev 
+        id: checkout_engine_rev
         if: ${{ inputs.duckdb-sha != '' }}
+        working-directory: .git/duckdb
         run: |
-          cd .git/duckdb && git checkout ${{ inputs.duckdb-sha }}
-
-      - uses: actions/setup-python@v5
-        with:
-          python-version: '3.12'
+          git checkout ${{ inputs.duckdb-sha }}
 
       - name: Vendor sources
         id: vendor
         run: |
-          export REV=$(cd .git/duckdb && git rev-parse --short HEAD && cd ../..)
-          echo "Updating vendored DuckDB sources to $REV"
+          REV=$(cd .git/duckdb && git rev-parse --short HEAD && cd ../..)
+          echo "Updating vendored DuckDB sources to ${REV}"
           git config --global user.email "github_bot@duckdblabs.com"
           git config --global user.name "DuckDB Labs GitHub Bot"
+          # Vendoring branch must exist, it may or may not already have
+          # a pending PR on it, we are rebasing it anyway
           git checkout vendoring
           git rebase ${{ github.ref_name }}
+          # Call the vendoring script in the engine
           git rm -rf src/duckdb
           python vendor.py --duckdb .git/duckdb
           git add src/duckdb CMakeLists.txt
+          # Clean up
           rm -rf .git/duckdb
-          git commit -m "Update vendored DuckDB sources to $REV"
-          git push -f --dry-run origin vendoring
+          # Export vendor revision for use in later steps
+          echo "vendor_rev=${REV}" >> "${GITHUB_OUTPUT}"
+
+      - name: Commit and push the changes
+        id: commit_and_push
+        if: ${{ steps.vendor.outcome == 'success' }}
+        run: |
+          MSG="Update vendored DuckDB sources to ${REV}"
+          git commit -m "${MSG}"
           # Check if ahead of upstream branch
           # If yes, set a step output
+          git push -f --dry-run origin vendoring
           if [ $(git rev-list HEAD...origin/main --count) -gt 0 ]; then
+            git push -f origin vendoring
             # Avoid set-output, it's deprecated
-            echo "vendor=$REV" >> "$GITHUB_OUTPUT"
+            echo "push_performed=true" >> "${GITHUB_OUTPUT}"
+            echo "commit_msg=${MSG}" >> "${GITHUB_OUTPUT}"
           fi
 
-      - name: Push the changes
-        if: steps.vendor.outputs.vendor != '' && github.event_name != 'pull_request'
+      - name: Auth GH CLI
+        id: auth_gh_cli
+        if: ${{ steps.commit_and_push.outputs.push_performed }}
         run: |
-          git push -f origin vendoring
+          # Store the PAT in a file that can be accessed by the
+          # GitHub CLI.
+          echo "${{ secrets.GITHUB_TOKEN }}" > token.txt
+          # Authorize GitHub CLI for the current repository
+          gh auth login --with-token < token.txt
 
-      - name: Create a PR
-        if: steps.vendor.outputs.vendor != '' && github.event_name != 'pull_request'
+      - name: Check PR exists
+        id: check_pr_exists
+        if: ${{ steps.auth_gh_cli.outcome == 'success' }}
         run: |
-            export MSG="$(git show -s --format=%s)"
-            # Store the PAT in a file that can be accessed by the
-            # GitHub CLI.
-            echo "${{ secrets.GH_TOKEN }}" > token.txt
-            # Authorize GitHub CLI for the current repository and
-            # create a pull-requests containing the updates.
-            gh auth login --with-token < token.txt
+          PR_NUM=$(gh pr list --head vendoring --json number --jq '.[].number')
+          if [ -z "$PR_NUM" ]; then
+            echo "No PR exists for branch vendoring"
+            echo "pr_exists=false" >> "$GITHUB_OUTPUT"
+          else
+            echo "PR found for branch vendoring, number: $PR_NUM"
+            echo "pr_exists=true" >> "$GITHUB_OUTPUT"
+            echo "pr_num=$PR_NUM" >> "$GITHUB_OUTPUT"
+          fi
+
+      - name: Create PR
+        id: create_pr
+        if: ${{ steps.check_pr_exists.outcome == 'success' && !steps.check_pr_exists.outputs.pr_num }}
+        run: |
             # This command will fail if PR already exists on vendoring branch
             gh pr create \
-             --title "${MSG}" \
+             --title "${{ steps.vendor.outputs.commit_msg }}" \
              --body "Changes:" \
              --head "vendoring" \
-             --base "main" || true
-            # Write existing body text to a file
+             --base "main" \
+             || true
+
+      - name: Update PR
+        id: update_pr
+        if: ${{ steps.check_pr_exists.outcome == 'success' && steps.check_pr_exists.outputs.pr_num }}
+        run: |
+            # Write existing PR body text to a file
             gh pr view vendoring --json body --jq '.body' > body.txt
             # Append change details to the body file
-            echo " - $(date +"%Y-%m-%d %H:%M:%S"): [duckdb/duckdb#${{ steps.vendor.outputs.vendor }}](https://github.com/duckdb/duckdb/commit/${{ steps.vendor.outputs.vendor }})" >> body.txt
+            DATE="$(date +"%Y-%m-%d %H:%M:%S")"
+            CHANGE_LABEL="duckdb/duckdb#${{ steps.vendor.outputs.vendor }}"
+            CHANGE_URL="https://github.com/duckdb/duckdb/commit/${{ steps.vendor.outputs.vendor }}"
+            echo " - ${DATE} [${CHANGE_LABEL}](${CHANGE_URL})" >> body.txt
             # Remove empty lines
             sed -i '/^$/d' body.txt
-            gh pr edit vendoring \
-             --title "${MSG}" \
+            gh pr edit ${{ steps.check_pr_exists.outputs.pr_num }} \
+             --title "${{ steps.vendor.outputs.commit_msg }}" \
              --body-file body.txt 
-            gh pr comment vendoring \
-             --body "${MSG}"
+            # Close and re-open the PR to trigger the tests
+            gh pr close ${{ steps.check_pr_exists.outputs.pr_num }}
+            gh pr reopen ${{ steps.check_pr_exists.outputs.pr_num }}
